### ISSUE TITLE
403 ForbiddenError when trying driver install

### ISSUE THREAD

**Issue by Seong-Yeol-Park** [SmartThingsCommunity/edge-cli-plugin#38]
**Describe the bug**

403 ForbiddenError when trying driver install

**To Reproduce**

`PS D:\smartthings-sdk> .\smartthings edge:drivers:install
┌───┬─────────────────┬────────────────────┬──────────────────────────────────────┐
│ # │ Label           │ Name               │ Device Id                            │
├───┼─────────────────┼────────────────────┼──────────────────────────────────────┤
│ 1 │ SmartThings Hub │ SmartThings v3 Hub │ 56a92ab1-02a2-4fc4-9f97-0ddf13fa992b │
└───┴─────────────────┴────────────────────┴──────────────────────────────────────┘
? Select a hub to install to. 1
    Error: Request failed with status code 403: {"requestId":"1DF91852-CD03-4527-81CB-E57DD3843D69","error":{"code":"ForbiddenError","message":"Forbidden","details":[]}}`

**Expected behavior**

installed without error

**Actual behavior**
A clear and concise description of what actually happens.

403 ForbiddenError when trying driver install

**Additional context**

My PC is windows 10
@smartthings/cli/0.0.0-pre.41 win32-x64 node-v12.18.1
other edge commands working well but only install command makes the above error

**Comment by john-u** [comment]
There is a known limitation with some Edge endpoints that do not accept the scopes currently available for Personal Access Tokens. Teams are working on a fix for this. If you remove the `token` from your CLI config, the default login flow should open a browser for authorization and this will authenticate the CLI correctly to successfully install drivers. The OAuth login is the preferred auth method going forward unless the CLI is being used in a headless environment where a browser is not available.

**Comment by rossiam** [comment]
This issue has been resolved. You should be able to use either a PAT or the regular login flow for all edge commands. If you come across any more 403s, please bring them to our attention. Thanks!
